{% set name = "tink" %}
{% set version = "1.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tink-{{ version }}.tar.gz
  sha256: 43cf7dd1e77c3c55538083cd416c5c6f1958d601eaf11d8997d0d60f24f90653

build:
  number: 0
  skip: True  # [py<38]
  # bazel is not available on linux-s390x
  skip: True  # [s390x]

requirements:
  build:
    - bazel >=6.4.0,<7
    - protobuf >=3.20.2,<5.0.0.dev0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - absl-py >=1.3.0
    - protobuf >=3.20.2,<5.0.0.dev0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5
    #- pybind11
  run_constrained: 
    # Extra: awskms
    - boto3 >=1.26.89
    # Extra: gcpkms
    - google-auth >=2.16.2
    - google-api-core >=2.11.0
    - google-cloud-kms >=2.16.1
    # Extra: hcvault
    - hvac >=1.1.1

test:
  imports:
    - tink
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tink-crypto/tink-py
  summary: A multi-language, cross-platform library that provides cryptographic APIs that are secure, easy to use correctly, and hard(er) to misuse.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  doc_url: https://developers.google.com/tink
  dev_url: https://github.com/tink-crypto/tink-py
  description: |
    Using crypto in your application shouldn't have to feel like juggling chainsaws in the dark.
    Tink is a crypto library written by a group of cryptographers and security engineers at Google. 
    It was born out of our extensive experience working with Google's product teams, fixing weaknesses in implementations, and providing simple APIs that can be used safely without needing a crypto background.
    Tink provides secure APIs that are easy to use correctly and hard(er) to misuse. 
    It reduces common crypto pitfalls with user-centered design, careful implementation and code reviews, and extensive testing. 
    At Google, Tink is one of the standard crypto libraries, and has been deployed in hundreds of products and systems.

extra:
  recipe-maintainers:
    - snegireff
